from .read_metadata import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_1, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_1
from .read_image import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2
from .show_text import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_3, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_3

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_1, **NODE_CLASS_MAPPINGS_2, **NODE_CLASS_MAPPINGS_3}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_1, **NODE_DISPLAY_NAME_MAPPINGS_2, **NODE_DISPLAY_NAME_MAPPINGS_3}

WEB_DIRECTORY = "./web"
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', "WEB_DIRECTORY"]
